### ISSUE TITLE
Homebrew warning

### ISSUE THREAD

**Issue by willian** [arl/homebrew-arl#1]
I started getting this error, and I think it is because of this: https://github.com/arl/homebrew-arl/commit/d8fa369f1e39c18ceb91be1be8eb800950535f8e

Error:
```shell
Warning: Found Ruby file outside arl/arl tap formula directory.
(/opt/homebrew/Library/Taps/arl/homebrew-arl/Formula):
  /opt/homebrew/Library/Taps/arl/homebrew-arl/gitmux.rb
```

Maybe the `gitmux.rb` should be moved and lived only inside the `Formula` directory. Any thoughts?

**Comment by arl** [comment]
Thank you for reporting.
I think this happened when I've updated goreleaser to v2. Something might have changed which I've missed when it comes to the generation of the Formula

**Comment by arl** [comment]
Indeed gitmux.rb is now generated inside the Formula directory.
The one remaining in the repo root comes from previous goreleaser version. I think we can remove it.

I'll go ahead and remove it. I don't have a Mac at home, can you try to reinstall gitmux normally and let me know if this still happens?

**Comment by willian** [comment]
Thanks, @arl
